name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  pre_ci:
    name: Prepare CI environment
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.continue.outputs.continue }}
    steps:
      - id: continue
        run: echo "continue=true" >> $GITHUB_OUTPUT

  test:
    name: Run Tests
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose
        id: run_tests

      - name: Update README test badge
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            sed -i 's/tests-failing-red/tests-passing-green/g' README.md
          else
            sed -i 's/tests-passing-green/tests-failing-red/g' README.md
          fi
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update tests badge in README [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy,rustc-dev
      - run: cargo clippy --all-features --tests --benches -- -Dclippy::all -Dclippy::pedantic

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1

  build:
    name: Build Project
    needs: [test, clippy, outdated]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cargo build --release --verbose --bin crabodex_cli
          mv target/release/crabodex_cli target/release/crabodex
        id: build

      - name: List build artifacts
        run: |
          echo "Contents of target/release:"
          ls -l target/release

      - name: Update README build badge
        run: |
          if [ "${{ steps.build.outcome }}" == "success" ]; then
            sed -i 's/build-failing-red/build-passing-green/g' README.md
          else
            sed -i 's/build-passing-green/build-failing-red/g' README.md
          fi
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update build badge in README [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: crabodex
          path: target/release/crabodex

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: crabodex

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./crabodex
          asset_name: crabodex
          asset_content_type: application/octet-stream